# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

# enable automatic code signing
enable_automatic_code_signing

ENV["FASTLANE_XCODEBUILD_SETTINGS_RETRIES"] = "10"

platform :ios do
  desc "Push a new beta build to TestFlight"
  lane :beta do
    increment_build_number(xcodeproj: "Pumpables.xcodeproj")
    build_app(workspace: "Pumpables.xcworkspace", scheme: "Pumpables")
    upload_to_testflight
  end
end
